# ===========================================
# roles/user_management/defaults/main.yml
# ===========================================
---
# Default fallback in case users are not defined
users: []

# These are the default user settings that will be applied to all users created by the playbook.
default_user_settings:
  state: present                     # Can be overwritten by state: absent
  group: users                       # Default group for all created users.
  create_home: true                  # Create or replace home directory.
  move_home: false                   # Do not move home_dir to a new path.
  system: false                      # Not a system account.
  append: false                      # Only add users to groups defined in groups:
  generate_ssh_key: false            # Generate user's ssh-keys. Since force=true, we will be generating ssh-keys each an every time the playbook is ran. 
  ssh_key_bits: 4096                 # Preference should be to use SSH keys with 4096 bits or more for security.
  ssh_key_type: rsa                  # Type of SSH key to generate. Options: rsa, dsa, ecdsa, ed25519.
  password_expire_max: 31            # Maximum number of days between password change.
  password_expire_min: 5             # Minimum number of days between password change.
  password_expire_warn: 7            # Number of days of warning before password expires.
  password_expire_account_disable: 5 # Disable the account after 5 days when the password expires.
  update_password: "always"          # will update passwords if they differ. Set this to on_create if you want to set the password for newly created users.
  force: true                        # This only affects state=absent, it forces removal of the user and associated directories. When used with generate_ssh_key=yes this forces an existing key to be overwritten.
  remove_home: false                 # Do not remove the user's home_dir.
  password_lock: false               # Do not lock user password. Note that users can still login using other methods, eg. ssh-keys
  remove: yes                        # This only affects state=absent, it attempts to remove directories associated with the user. The behavior is the same as userdel --remove
  shell: /bin/bash                   # Default shell for all users