#!/usr/bin/env python3
"""
Reproducible Kubernetes Aggregate Inventory Generator.

Discovers k8s control plane, etcd, and worker nodes across environment
inventories (or terraform outputs) and renders an authoritative, reproducible
Kubespray inventory at inventories/k8s/inventory.ini.

Validates:
- Exact group cardinality (control plane >= 1, etcd >= 1, workers >= 1).
- Topology failure domain awareness.
- Explicit non-HA notification when single control plane or etcd is used.
"""

import argparse
import json
import os
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Set


def parse_inventory_for_k8s_nodes(inventory_file: Path) -> List[Dict[str, str]]:
    """Extract Kubernetes nodes from an Ansible inventory INI file."""
    if not inventory_file.is_file():
        return []

    nodes: List[Dict[str, str]] = []
    current_section = None

    with open(inventory_file, "r", encoding="utf-8") as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line or line.startswith(("#", ";")):
                continue

            if line.startswith("[") and line.endswith("]"):
                current_section = line[1:-1].strip()
                continue

            # Check if line contains a host definition
            tokens = line.split()
            if not tokens:
                continue

            hostname = tokens[0]
            attrs: Dict[str, str] = {"hostname": hostname}
            for token in tokens[1:]:
                if "=" in token:
                    k, v = token.split("=", 1)
                    attrs[k] = v

            role = attrs.get("node_role", "")
            if not role and current_section:
                if current_section in ["k8s_control_plane", "kube_control_plane"]:
                    role = "k8s_control_plane"
                elif current_section in ["k8s_etcd", "etcd"]:
                    role = "k8s_etcd"
                elif current_section in ["k8s_workers", "kube_node"]:
                    role = "k8s_workers"

            if role in ["k8s_control_plane", "k8s_etcd", "k8s_workers", "kube_control_plane", "kube_node", "etcd"]:
                attrs["role"] = role
                nodes.append(attrs)

    return nodes


def generate_k8s_inventory(
    source_inventories: List[Path],
    output_path: Path,
    ssh_user: str = "ansible",
    ssh_key: str = "~/.ssh/id_rsa",
) -> Dict[str, any]:
    """Aggregate discovered nodes and generate inventories/k8s/inventory.ini."""
    all_nodes: Dict[str, Dict[str, str]] = {}

    for inv in source_inventories:
        discovered = parse_inventory_for_k8s_nodes(inv)
        for node in discovered:
            h = node["hostname"]
            # Deduplicate or merge
            if h not in all_nodes:
                all_nodes[h] = node
            else:
                all_nodes[h].update(node)

    control_plane_nodes: List[str] = []
    etcd_nodes: List[str] = []
    worker_nodes: List[str] = []

    for h, node in sorted(all_nodes.items()):
        role = node.get("role", "")
        if role in ["k8s_control_plane", "kube_control_plane"]:
            control_plane_nodes.append(h)
        elif role in ["k8s_etcd", "etcd"]:
            etcd_nodes.append(h)
        elif role in ["k8s_workers", "kube_node"]:
            worker_nodes.append(h)

    # Validate topology requirements
    if not control_plane_nodes:
        raise ValueError("No Kubernetes control plane nodes found in source inventories.")
    if not etcd_nodes and not control_plane_nodes:
        raise ValueError("No etcd nodes found and no control plane nodes to host stacked etcd.")
    if not worker_nodes:
        raise ValueError("No Kubernetes worker nodes found in source inventories.")

    # Etcd assignment: if no dedicated etcd nodes, stack on control plane
    effective_etcd_nodes = etcd_nodes if etcd_nodes else control_plane_nodes

    is_ha = len(control_plane_nodes) >= 3 and len(effective_etcd_nodes) >= 3
    topology_notice = "HIGH-AVAILABILITY (HA)" if is_ha else "NON-HA (Single control-plane / etcd lab profile)"

    # Build INI content
    lines: List[str] = [
        "# Ansible inventory for Kubernetes cluster across Proxmox nodes",
        "# Automatically generated by terraform-proxmox/scripts/generate-k8s-inventory.py",
        f"# Topology Architecture: {topology_notice}",
        f"# Control plane count: {len(control_plane_nodes)}, etcd count: {len(effective_etcd_nodes)}, worker count: {len(worker_nodes)}",
        "",
        "[all:vars]",
        f"ansible_user={ssh_user}",
        f"ansible_ssh_private_key_file={ssh_key}",
        "ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new -o ControlMaster=auto -o ControlPersist=60s'",
        "ansible_python_interpreter=/usr/bin/python3",
        "ansible_become=yes",
        "ansible_become_method=sudo",
        "ansible_ssh_timeout=30",
        "ansible_gather_timeout=30",
        "",
        "[all]",
    ]

    etcd_idx = 1
    for h in sorted(all_nodes.keys()):
        node = all_nodes[h]
        ansible_host = node.get("ansible_host", "")
        ip_val = node.get("ip", ansible_host)
        line = f"{h} ansible_host={ansible_host} ip={ip_val}"
        if h in effective_etcd_nodes:
            line += f" etcd_member_name=etcd{etcd_idx}"
            etcd_idx += 1
        lines.append(line)

    lines.extend([
        "",
        "[k8s_control_plane]",
        *[h for h in sorted(control_plane_nodes)],
        "",
        "[k8s_etcd]",
        *[h for h in sorted(effective_etcd_nodes)],
        "",
        "[k8s_workers]",
        *[h for h in sorted(worker_nodes)],
        "",
        "[kube_control_plane]",
        *[h for h in sorted(control_plane_nodes)],
        "",
        "[etcd]",
        *[h for h in sorted(effective_etcd_nodes)],
        "",
        "[kube_node]",
        *[h for h in sorted(worker_nodes)],
        "",
        "[k8s_cluster:children]",
        "kube_control_plane",
        "kube_node",
        "",
        "[calico_rr]",
        "",
    ])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    return {
        "status": "GENERATED",
        "output_path": str(output_path),
        "is_ha": is_ha,
        "control_plane_count": len(control_plane_nodes),
        "etcd_count": len(effective_etcd_nodes),
        "worker_count": len(worker_nodes),
        "nodes": sorted(all_nodes.keys()),
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate Kubespray aggregate inventory from environment inventories"
    )
    parser.add_argument(
        "--source-inventories",
        nargs="+",
        help="Source inventory files to scan (default: inventories/example/inventory.ini inventories/optiplex/inventory.ini)",
    )
    parser.add_argument(
        "--output",
        default="inventories/k8s/inventory.ini",
        help="Target Kubespray inventory path (default: inventories/k8s/inventory.ini)",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print machine-readable JSON output",
    )

    args = parser.parse_args()
    repo_root = Path(__file__).resolve().parents[2]

    sources: List[Path] = []
    if args.source_inventories:
        for p in args.source_inventories:
            sources.append(Path(p).resolve())
    else:
        # Default discovery: prioritize deployed cluster inventories over template dev
        deployed_candidates = [
            repo_root / "inventories/example/inventory.ini",
            repo_root / "inventories/optiplex/inventory.ini",
        ]
        active_deployed = [c for c in deployed_candidates if c.is_file()]
        if active_deployed:
            sources = active_deployed
        else:
            dev_candidate = repo_root / "inventories/example/inventory.ini"
            if dev_candidate.is_file():
                sources = [dev_candidate]

    output_path = (repo_root / args.output) if not Path(args.output).is_absolute() else Path(args.output)

    try:
        summary = generate_k8s_inventory(sources, output_path)
        if args.json:
            print(json.dumps(summary, indent=2))
        else:
            print(f"Successfully generated Kubespray aggregate inventory at {summary['output_path']}")
            print(f"Topology: {'HA' if summary['is_ha'] else 'NON-HA (Lab/Dev Profile)'}")
            print(f"Nodes: {len(summary['nodes'])} total ({summary['control_plane_count']} CP, {summary['etcd_count']} etcd, {summary['worker_count']} workers)")
        return 0
    except Exception as e:
        print(f"Error generating k8s aggregate inventory: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
