#!/usr/bin/env bash
# Scaffold a new Terraform/Packer environment from an existing template env.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

ENVIRONMENT="${ENVIRONMENT:-}"
TEMPLATE_ENV="${TEMPLATE_ENV:-dev}"
PROXMOX_HOST="${PROXMOX_HOST:-}"
PROXMOX_USER="${PROXMOX_USER:-root}"
PROXMOX_NODE="${PROXMOX_NODE:-}"
ANSIBLE_HOST="${ANSIBLE_HOST:-}"
NETWORK_CIDR="${NETWORK_CIDR:-}"
NETWORK_GW="${NETWORK_GW:-}"
NETWORK_BRIDGE="${NETWORK_BRIDGE:-}"
STORAGE_POOL="${STORAGE_POOL:-}"
DATA_STORAGE="${DATA_STORAGE:-}"
BASE_VM_OS_STORAGE="${BASE_VM_OS_STORAGE:-}"
BASE_VM_DATA_STORAGE="${BASE_VM_DATA_STORAGE:-}"
BASE_VM_EFI_STORAGE="${BASE_VM_EFI_STORAGE:-}"
BASE_VM_CI_STORAGE="${BASE_VM_CI_STORAGE:-}"
BASE_VM_SNIPPET_STORAGE="${BASE_VM_SNIPPET_STORAGE:-}"
AUTO_DISCOVER="${AUTO_DISCOVER:-false}"
FORCE=false

# Reserved VMID/name policy for reusable base VMs and Packer output templates.
BASE_VMID_ORACLE9=999999990
BASE_VMID_ORACLE8=999999991
BASE_VMID_UBUNTU2404=999999992
TEMPLATE_VMID_ORACLE9=999999993
TEMPLATE_VMID_ORACLE8=999999994
TEMPLATE_VMID_UBUNTU2404=999999995
TEMPLATE_NAME_ORACLE9="oracle9-template"
TEMPLATE_NAME_ORACLE8="oracle8-template"
TEMPLATE_NAME_UBUNTU2404="ubuntu2404-template"

usage() {
  cat <<'EOF'
Usage:
  scaffold-env.sh --environment <name> [options]

Options:
  --environment <name>   New environment name (for example: qa).
  --template-env <name>  Existing env used as source template (default: dev).
  --proxmox-host <host>  Proxmox host/IP for this env (optional).
  --proxmox-user <name>  Proxmox SSH user for discovery (default: root).
  --proxmox-node <name>  Proxmox node name in tfvars/packer vars (optional).
  --ansible-host <host>  Ansible host/IP metadata for this env (optional).
  --network-cidr <cidr>  CIDR used to rewrite ipconfig0 IP/prefix (optional).
  --network-gw <ip>      Gateway used to rewrite ipconfig0 gw= (optional).
  --network-bridge <br>  Terraform network_bridge value (optional).
  --storage-pool <name>  Terraform storage_pool value (optional).
  --data-storage <name>  Terraform data_disk_defaults.storage value (optional).
  --auto-discover        Discover node/storage/network defaults from Proxmox over SSH.
  --force                Overwrite existing generated files.
  -h, --help             Show this help.

Environment variable equivalents are also supported:
  ENVIRONMENT, TEMPLATE_ENV, PROXMOX_HOST, PROXMOX_USER, PROXMOX_NODE, ANSIBLE_HOST, NETWORK_CIDR, NETWORK_GW
  NETWORK_BRIDGE, STORAGE_POOL, DATA_STORAGE, BASE_VM_OS_STORAGE, BASE_VM_DATA_STORAGE
  BASE_VM_EFI_STORAGE, BASE_VM_CI_STORAGE, BASE_VM_SNIPPET_STORAGE, AUTO_DISCOVER
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --environment)
      ENVIRONMENT="${2:-}"
      shift 2
      ;;
    --template-env)
      TEMPLATE_ENV="${2:-}"
      shift 2
      ;;
    --proxmox-host)
      PROXMOX_HOST="${2:-}"
      shift 2
      ;;
    --proxmox-user)
      PROXMOX_USER="${2:-}"
      shift 2
      ;;
    --proxmox-node)
      PROXMOX_NODE="${2:-}"
      shift 2
      ;;
    --ansible-host)
      ANSIBLE_HOST="${2:-}"
      shift 2
      ;;
    --network-cidr)
      NETWORK_CIDR="${2:-}"
      shift 2
      ;;
    --network-gw)
      NETWORK_GW="${2:-}"
      shift 2
      ;;
    --network-bridge)
      NETWORK_BRIDGE="${2:-}"
      shift 2
      ;;
    --storage-pool)
      STORAGE_POOL="${2:-}"
      shift 2
      ;;
    --data-storage)
      DATA_STORAGE="${2:-}"
      shift 2
      ;;
    --auto-discover)
      AUTO_DISCOVER=true
      shift
      ;;
    --force)
      FORCE=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Error: unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

require_non_empty() {
  local value="$1"
  local name="$2"
  if [[ -z "${value}" ]]; then
    echo "Error: ${name} is required." >&2
    exit 1
  fi
}

escape_sed_repl() {
  printf '%s' "$1" | sed -e 's/[\/&]/\\&/g'
}

upsert_env_key() {
  local file="$1"
  local key="$2"
  local value="$3"
  local escaped
  escaped="$(escape_sed_repl "${value}")"

  if [[ -f "${file}" ]] && grep -q "^${key}=" "${file}"; then
    sed -i -E "s#^${key}=.*#${key}=${escaped}#" "${file}"
  else
    {
      if [[ ! -f "${file}" ]]; then
        echo "# Local environment values (generated by scaffold-env.sh)"
      fi
      echo "${key}=${value}"
    } >> "${file}"
  fi
}

maybe_discover_defaults() {
  local discovery_script discovery_file
  discovery_script="${SCRIPT_DIR}/discover-proxmox-core.sh"

  if [[ "${AUTO_DISCOVER}" != true ]]; then
    return 0
  fi
  if [[ -z "${PROXMOX_HOST}" ]]; then
    echo "Warning: AUTO_DISCOVER=true but PROXMOX_HOST is empty; skipping discovery." >&2
    return 0
  fi
  if [[ ! -x "${discovery_script}" ]]; then
    echo "Warning: discovery script missing or not executable: ${discovery_script}" >&2
    return 0
  fi

  discovery_file="$(mktemp)"
  if ! "${discovery_script}" --host "${PROXMOX_HOST}" --user "${PROXMOX_USER}" --env > "${discovery_file}"; then
    echo "Warning: auto-discovery failed for ${PROXMOX_USER}@${PROXMOX_HOST}; continuing with provided/manual values." >&2
    rm -f "${discovery_file}"
    return 0
  fi

  # shellcheck disable=SC1090
  set -a
  source "${discovery_file}"
  set +a

  rm -f "${discovery_file}"
}

rewrite_network() {
  local file="$1"
  local cidr="$2"
  local gw="$3"

  if [[ -n "${cidr}" ]]; then
    local ip prefix base
    ip="${cidr%/*}"
    prefix="${cidr#*/}"
    base="$(awk -F. '{print $1"."$2"."$3}' <<< "${ip}")"

    if [[ "${ip}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] && [[ "${prefix}" =~ ^[0-9]+$ ]]; then
      sed -i -E "s#ip=[0-9]+\.[0-9]+\.[0-9]+\.([0-9]+)/[0-9]+#ip=${base}.\\1/${prefix}#g" "${file}"
    else
      echo "Warning: NETWORK_CIDR '${cidr}' is not valid IPv4 CIDR; skipping ipconfig0 rewrite." >&2
    fi
  fi

  if [[ -n "${gw}" ]]; then
    if [[ "${gw}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      sed -i -E "s#gw=[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+#gw=${gw}#g" "${file}"
    else
      echo "Warning: NETWORK_GW '${gw}' is not a valid IPv4 address; skipping gateway rewrite." >&2
    fi
  fi
}

set_data_disk_storage_in_tfvars() {
  local file="$1"
  local value="$2"
  local tmp
  tmp="$(mktemp)"
  awk -v storage_value="${value}" '
    BEGIN { in_block = 0; updated = 0 }
    /^[[:space:]]*data_disk_defaults[[:space:]]*=[[:space:]]*{/ { in_block = 1; print; next }
    in_block && /^[[:space:]]*}/ { in_block = 0; print; next }
    in_block && /^[[:space:]]*storage[[:space:]]*=/ {
      print "  storage = \"" storage_value "\""
      updated = 1
      next
    }
    { print }
    END {
      if (updated == 0) {
        # no-op; caller can decide if this is expected.
      }
    }
  ' "${file}" > "${tmp}"
  mv "${tmp}" "${file}"
}

set_string_tfvar() {
  local file="$1"
  local key="$2"
  local value="$3"
  local tmp

  tmp="$(mktemp)"
  awk -v tf_key="${key}" -v tf_value="${value}" '
    BEGIN { updated = 0 }
    $0 ~ "^[[:space:]]*" tf_key "[[:space:]]*=" {
      print tf_key " = \"" tf_value "\""
      updated = 1
      next
    }
    { print }
    END {
      if (updated == 0) {
        print tf_key " = \"" tf_value "\""
      }
    }
  ' "${file}" > "${tmp}"
  mv "${tmp}" "${file}"
}

derive_network_cidr_from_host_cidr() {
  local host_cidr="$1"
  local host_ip prefix
  host_ip="${host_cidr%/*}"
  prefix="${host_cidr#*/}"

  if command -v ipcalc >/dev/null 2>&1; then
    ipcalc -n "${host_cidr}" 2>/dev/null | awk -F': *' '/^Network:/ {print $2; exit}'
    return 0
  fi

  if [[ "${host_ip}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ && "${prefix}" == "24" ]]; then
    awk -F. -v p="${prefix}" '{print $1"."$2"."$3".0/"p}' <<< "${host_ip}"
    return 0
  fi

  printf '%s\n' ""
}

require_non_empty "${ENVIRONMENT}" "ENVIRONMENT"
maybe_discover_defaults

if [[ -z "${PROXMOX_NODE}" ]]; then
  PROXMOX_NODE="${DISCOVERED_PROXMOX_NODE:-}"
fi
if [[ -z "${ANSIBLE_HOST}" ]]; then
  ANSIBLE_HOST="${DISCOVERED_ANSIBLE_HOST:-}"
fi
if [[ -z "${NETWORK_BRIDGE}" ]]; then
  NETWORK_BRIDGE="${DISCOVERED_NETWORK_BRIDGE:-}"
fi
if [[ -z "${NETWORK_GW}" ]]; then
  NETWORK_GW="${DISCOVERED_PROXMOX_DEFAULT_GATEWAY:-${NETWORK_GW}}"
fi
if [[ -z "${NETWORK_CIDR}" && -n "${DISCOVERED_BRIDGE_IPCIDR:-}" ]]; then
  NETWORK_CIDR="$(derive_network_cidr_from_host_cidr "${DISCOVERED_BRIDGE_IPCIDR}")"
fi
if [[ -z "${STORAGE_POOL}" ]]; then
  STORAGE_POOL="${DISCOVERED_STORAGE_POOL:-}"
fi
if [[ -z "${DATA_STORAGE}" ]]; then
  DATA_STORAGE="${DISCOVERED_DATA_STORAGE:-${STORAGE_POOL}}"
fi
if [[ -z "${BASE_VM_OS_STORAGE}" ]]; then
  BASE_VM_OS_STORAGE="${DISCOVERED_BASE_VM_OS_STORAGE:-${STORAGE_POOL}}"
fi
if [[ -z "${BASE_VM_DATA_STORAGE}" ]]; then
  BASE_VM_DATA_STORAGE="${DISCOVERED_BASE_VM_DATA_STORAGE:-${BASE_VM_OS_STORAGE}}"
fi
if [[ -z "${BASE_VM_EFI_STORAGE}" ]]; then
  BASE_VM_EFI_STORAGE="${DISCOVERED_BASE_VM_EFI_STORAGE:-${BASE_VM_OS_STORAGE}}"
fi
if [[ -z "${BASE_VM_CI_STORAGE}" ]]; then
  BASE_VM_CI_STORAGE="${DISCOVERED_BASE_VM_CI_STORAGE:-${BASE_VM_OS_STORAGE}}"
fi
if [[ -z "${BASE_VM_SNIPPET_STORAGE}" ]]; then
  BASE_VM_SNIPPET_STORAGE="${DISCOVERED_BASE_VM_SNIPPET_STORAGE:-local}"
fi

if [[ ! "${ENVIRONMENT}" =~ ^[a-z0-9][a-z0-9-]*$ ]]; then
  echo "Error: ENVIRONMENT must match ^[a-z0-9][a-z0-9-]*$" >&2
  exit 1
fi

template_tfvars="${REPO_ROOT}/environments/${TEMPLATE_ENV}.tfvars"
target_tfvars="${REPO_ROOT}/environments/${ENVIRONMENT}.tfvars"
bootstrap_env="${REPO_ROOT}/environments/${ENVIRONMENT}.bootstrap.env"
env_file="${REPO_ROOT}/.env"

if [[ ! -f "${template_tfvars}" ]]; then
  echo "Error: template tfvars not found: ${template_tfvars}" >&2
  exit 1
fi

if [[ -f "${target_tfvars}" && "${FORCE}" != true ]]; then
  echo "Error: ${target_tfvars} already exists. Re-run with --force to overwrite." >&2
  exit 1
fi

if [[ -f "${bootstrap_env}" && "${FORCE}" != true ]]; then
  echo "Error: ${bootstrap_env} already exists. Re-run with --force to overwrite." >&2
  exit 1
fi

cp "${template_tfvars}" "${target_tfvars}"

env_escaped="$(escape_sed_repl "${ENVIRONMENT}")"
template_escaped="$(escape_sed_repl "${TEMPLATE_ENV}")"
cluster_name="${ENVIRONMENT}-cluster"
cluster_escaped="$(escape_sed_repl "${cluster_name}")"

sed -i -E "s#^(environment_name[[:space:]]*=[[:space:]]*\").*(\"[[:space:]]*)\$#\\1${env_escaped}\\2#" "${target_tfvars}"
sed -i -E "s#^(cluster_name[[:space:]]*=[[:space:]]*\").*(\"[[:space:]]*)\$#\\1${cluster_escaped}\\2#" "${target_tfvars}"

if [[ "${TEMPLATE_ENV}" != "${ENVIRONMENT}" ]]; then
  sed -i -E "s#${template_escaped}-#${env_escaped}-#g" "${target_tfvars}"
fi

if [[ -n "${PROXMOX_NODE}" ]]; then
  node_escaped="$(escape_sed_repl "${PROXMOX_NODE}")"
  sed -i -E "s#^(target_node[[:space:]]*=[[:space:]]*\").*(\"[[:space:]]*)\$#\\1${node_escaped}\\2#" "${target_tfvars}"
fi
if [[ -n "${NETWORK_BRIDGE}" ]]; then
  bridge_escaped="$(escape_sed_repl "${NETWORK_BRIDGE}")"
  sed -i -E "s#^(network_bridge[[:space:]]*=[[:space:]]*\").*(\"[[:space:]]*)\$#\\1${bridge_escaped}\\2#" "${target_tfvars}"
fi
if [[ -n "${STORAGE_POOL}" ]]; then
  storage_escaped="$(escape_sed_repl "${STORAGE_POOL}")"
  sed -i -E "s#^(storage_pool[[:space:]]*=[[:space:]]*\").*(\"[[:space:]]*)\$#\\1${storage_escaped}\\2#" "${target_tfvars}"
fi
if [[ -n "${BASE_VM_SNIPPET_STORAGE}" ]]; then
  set_string_tfvar "${target_tfvars}" "snippet_storage" "${BASE_VM_SNIPPET_STORAGE}"
fi
if [[ -n "${DATA_STORAGE}" ]]; then
  set_data_disk_storage_in_tfvars "${target_tfvars}" "${DATA_STORAGE}"
fi

rewrite_network "${target_tfvars}" "${NETWORK_CIDR}" "${NETWORK_GW}"

tmp_file="$(mktemp)"
{
  echo "# Generated from environments/${TEMPLATE_ENV}.tfvars by scripts/scaffold-env.sh"
  echo "# Review and edit this file before plan/apply (especially VMIDs, node_groups, storage, and IPs)."
  if [[ -n "${DISCOVERED_VMDISK_STORAGES:-}" ]]; then
    echo "# Auto-discovered VM-disk storage pools: ${DISCOVERED_VMDISK_STORAGES}"
  fi
  if [[ -n "${DISCOVERED_SNIPPET_STORAGES:-}" ]]; then
    echo "# Auto-discovered snippet storage pools: ${DISCOVERED_SNIPPET_STORAGES}"
  fi
  echo
  cat "${target_tfvars}"
} > "${tmp_file}"
mv "${tmp_file}" "${target_tfvars}"

for packer_dir in "ubuntu-noble" "oracle8" "oracle9"; do
  source_vars="${REPO_ROOT}/packer/${packer_dir}/vars.${TEMPLATE_ENV}.pkrvars.hcl"
  target_vars="${REPO_ROOT}/packer/${packer_dir}/vars.${ENVIRONMENT}.pkrvars.hcl"

  if [[ ! -f "${source_vars}" ]]; then
    source_vars="${REPO_ROOT}/packer/${packer_dir}/vars.example.pkrvars.hcl"
  fi
  if [[ ! -f "${source_vars}" ]]; then
    echo "Error: no source vars file found for packer/${packer_dir}." >&2
    exit 1
  fi
  if [[ -f "${target_vars}" && "${FORCE}" != true ]]; then
    echo "Error: ${target_vars} already exists. Re-run with --force to overwrite." >&2
    exit 1
  fi

  cp "${source_vars}" "${target_vars}"

  if [[ -n "${PROXMOX_HOST}" ]]; then
    host_escaped="$(escape_sed_repl "${PROXMOX_HOST}")"
    sed -i -E "s#^(proxmox_api_url[[:space:]]*=[[:space:]]*\"https://)[^\"]+(:8006/api2/json\"[[:space:]]*)\$#\\1${host_escaped}\\2#" "${target_vars}"
  fi
  if [[ -n "${PROXMOX_NODE}" ]]; then
    node_escaped="$(escape_sed_repl "${PROXMOX_NODE}")"
    sed -i -E "s#^(proxmox_node[[:space:]]*=[[:space:]]*\").*(\"[[:space:]]*)\$#\\1${node_escaped}\\2#" "${target_vars}"
  fi

  case "${packer_dir}" in
    ubuntu-noble)
      template_name="${TEMPLATE_NAME_UBUNTU2404}"
      template_vmid="${TEMPLATE_VMID_UBUNTU2404}"
      clone_vmid="${BASE_VMID_UBUNTU2404}"
      ;;
    oracle8)
      template_name="${TEMPLATE_NAME_ORACLE8}"
      template_vmid="${TEMPLATE_VMID_ORACLE8}"
      clone_vmid="${BASE_VMID_ORACLE8}"
      ;;
    oracle9)
      template_name="${TEMPLATE_NAME_ORACLE9}"
      template_vmid="${TEMPLATE_VMID_ORACLE9}"
      clone_vmid="${BASE_VMID_ORACLE9}"
      ;;
    *)
      template_name=""
      template_vmid=""
      clone_vmid=""
      ;;
  esac

  if [[ -n "${template_name}" ]]; then
    template_name_escaped="$(escape_sed_repl "${template_name}")"
    sed -i -E "s#^(template_name[[:space:]]*=[[:space:]]*\").*(\"[[:space:]]*)\$#\\1${template_name_escaped}\\2#" "${target_vars}"
  fi
  if [[ -n "${template_vmid}" ]]; then
    sed -i -E "s#^(vm_id[[:space:]]*=[[:space:]]*).*\$#\\1${template_vmid}#" "${target_vars}"
  fi
  if [[ -n "${clone_vmid}" ]]; then
    sed -i -E "s#^(clone_vm_id[[:space:]]*=[[:space:]]*).*\$#\\1${clone_vmid}#" "${target_vars}"
  fi
done

env_upper="$(printf '%s' "${ENVIRONMENT}" | tr '[:lower:]-' '[:upper:]_')"

if [[ -n "${PROXMOX_HOST}" ]]; then
  upsert_env_key "${env_file}" "PROXMOX_HOST_${env_upper}" "${PROXMOX_HOST}"
fi
if [[ -n "${PROXMOX_NODE}" ]]; then
  upsert_env_key "${env_file}" "PROXMOX_NODE_${env_upper}" "${PROXMOX_NODE}"
fi
if [[ -n "${ANSIBLE_HOST}" ]]; then
  upsert_env_key "${env_file}" "ANSIBLE_HOST_${env_upper}" "${ANSIBLE_HOST}"
fi
if [[ -n "${NETWORK_CIDR}" ]]; then
  upsert_env_key "${env_file}" "NETWORK_CIDR_${env_upper}" "${NETWORK_CIDR}"
fi
if [[ -n "${NETWORK_GW}" ]]; then
  upsert_env_key "${env_file}" "NETWORK_GW_${env_upper}" "${NETWORK_GW}"
fi
if [[ -n "${STORAGE_POOL}" ]]; then
  upsert_env_key "${env_file}" "STORAGE_POOL_${env_upper}" "${STORAGE_POOL}"
fi
if [[ -n "${DATA_STORAGE}" ]]; then
  upsert_env_key "${env_file}" "DATA_STORAGE_${env_upper}" "${DATA_STORAGE}"
fi

{
  echo "# Generated by scripts/scaffold-env.sh for ENVIRONMENT=${ENVIRONMENT}"
  echo "# Source this file before bootstrap commands:"
  echo "#   set -a; source environments/${ENVIRONMENT}.bootstrap.env; set +a"
  echo
  echo "ENVIRONMENT=${ENVIRONMENT}"
  echo "TEMPLATE_ENV=${TEMPLATE_ENV}"
  echo "AUTO_DISCOVER=${AUTO_DISCOVER}"
  echo "PROXMOX_HOST=${PROXMOX_HOST:-CHANGE_ME_PROXMOX_HOST}"
  echo "PROXMOX_USER=${PROXMOX_USER}"
  echo "PROXMOX_NODE=${PROXMOX_NODE:-CHANGE_ME_PROXMOX_NODE}"
  echo "ANSIBLE_HOST=${ANSIBLE_HOST:-CHANGE_ME_ANSIBLE_HOST}"
  echo "NETWORK_CIDR=${NETWORK_CIDR:-CHANGE_ME_NETWORK_CIDR}"
  echo "NETWORK_GW=${NETWORK_GW:-CHANGE_ME_NETWORK_GW}"
  echo "NETWORK_BRIDGE=${NETWORK_BRIDGE:-vmbr0}"
  echo "STORAGE_POOL=${STORAGE_POOL:-local-lvm}"
  echo "DATA_STORAGE=${DATA_STORAGE:-${STORAGE_POOL:-local-lvm}}"
  echo "VAULT_LAN_IP=${ANSIBLE_HOST:-CHANGE_ME_ANSIBLE_HOST}"
  echo "VAULT_LAN_HOST=${ANSIBLE_HOST:-CHANGE_ME_ANSIBLE_HOST}"
  echo
  echo "BASE_VM_BRIDGE=${NETWORK_BRIDGE:-vmbr0}"
  echo "AUTO_DOWNLOAD_IMAGE=true"
  echo "BASE_VM_IPCIDR=dhcp"
  echo "BASE_VM_GATEWAY=${NETWORK_GW:-}"
  echo "BASE_VM_DNS=198.51.100.23"
  echo "BASE_VM_OS_STORAGE=${BASE_VM_OS_STORAGE:-${STORAGE_POOL:-local-lvm}}"
  echo "BASE_VM_DATA_STORAGE=${BASE_VM_DATA_STORAGE:-${DATA_STORAGE:-${STORAGE_POOL:-local-lvm}}}"
  echo "BASE_VM_EFI_STORAGE=${BASE_VM_EFI_STORAGE:-${STORAGE_POOL:-local-lvm}}"
  echo "BASE_VM_CI_STORAGE=${BASE_VM_CI_STORAGE:-${STORAGE_POOL:-local-lvm}}"
  echo "BASE_VM_SNIPPET_STORAGE=${BASE_VM_SNIPPET_STORAGE:-local}"
  echo "BASE_VM_CORES=8"
  echo "BASE_VM_MEM=10240"
  echo "BASE_VM_OS_DISK_SIZE=50"
  echo "BASE_VM_CIUSER=ansible"
  echo
  echo "# Auto-discovered storage pools (comma-separated)"
  echo "DISCOVERED_VMDISK_STORAGES=${DISCOVERED_VMDISK_STORAGES:-${STORAGE_POOL}}"
  echo "DISCOVERED_SNIPPET_STORAGES=${DISCOVERED_SNIPPET_STORAGES:-${BASE_VM_SNIPPET_STORAGE}}"
} > "${bootstrap_env}"

discovery_summary_file="${REPO_ROOT}/environments/${ENVIRONMENT}.autodiscover.env"
{
  echo "# Generated by scripts/scaffold-env.sh (auto-discovery snapshot)"
  echo "DISCOVERED_PROXMOX_HOST=${DISCOVERED_PROXMOX_HOST:-${PROXMOX_HOST}}"
  echo "DISCOVERED_PROXMOX_NODE=${DISCOVERED_PROXMOX_NODE:-${PROXMOX_NODE}}"
  echo "DISCOVERED_ANSIBLE_HOST=${DISCOVERED_ANSIBLE_HOST:-${ANSIBLE_HOST}}"
  echo "DISCOVERED_NETWORK_BRIDGE=${DISCOVERED_NETWORK_BRIDGE:-${NETWORK_BRIDGE}}"
  echo "DISCOVERED_BRIDGE_IPCIDR=${DISCOVERED_BRIDGE_IPCIDR:-}"
  echo "DERIVED_NETWORK_CIDR=${NETWORK_CIDR:-}"
  echo "DISCOVERED_PROXMOX_DEFAULT_GATEWAY=${DISCOVERED_PROXMOX_DEFAULT_GATEWAY:-${NETWORK_GW}}"
  echo "DISCOVERED_STORAGE_POOL=${DISCOVERED_STORAGE_POOL:-${STORAGE_POOL}}"
  echo "DISCOVERED_DATA_STORAGE=${DISCOVERED_DATA_STORAGE:-${DATA_STORAGE}}"
  echo "DISCOVERED_BASE_VM_SNIPPET_STORAGE=${DISCOVERED_BASE_VM_SNIPPET_STORAGE:-${BASE_VM_SNIPPET_STORAGE}}"
  echo "DISCOVERED_VMDISK_STORAGES=${DISCOVERED_VMDISK_STORAGES:-${STORAGE_POOL}}"
  echo "DISCOVERED_SNIPPET_STORAGES=${DISCOVERED_SNIPPET_STORAGES:-${BASE_VM_SNIPPET_STORAGE}}"
} > "${discovery_summary_file}"

echo "Scaffold complete for ENVIRONMENT=${ENVIRONMENT}"
echo "  tfvars:      ${target_tfvars}"
echo "  bootstrap:   ${bootstrap_env}"
echo "  discovery:   ${discovery_summary_file}"
echo "  packer vars: packer/*/vars.${ENVIRONMENT}.pkrvars.hcl"
if [[ -n "${PROXMOX_HOST}" || -n "${ANSIBLE_HOST}" || -n "${NETWORK_CIDR}" || -n "${NETWORK_GW}" ]]; then
  echo "  updated:     ${env_file}"
fi
echo
echo "Next:"
echo "  1) Review/edit ${target_tfvars}"
echo "  2) Run: make env-bootstrap ENVIRONMENT=${ENVIRONMENT}"
echo "     (env-bootstrap auto-loads ${bootstrap_env} when present)"
