# Ansible inventory for ${environment}
# Generated by Terraform on ${timestamp}

# Global Ansible variables
[all:vars]
ansible_user=ansible
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new -o ControlMaster=auto -o ControlPersist=60s'
ansible_python_interpreter=/usr/bin/python3
ansible_become=yes
ansible_become_method=sudo
ansible_ssh_timeout=30
ansible_gather_timeout=30

# Environment and cluster metadata
cluster_environment=${environment}
cluster_name=${cluster_name}
%{ if length(common_tags) > 0 ~}
# Cluster tags from Terraform
%{ for key, value in common_tags ~}
cluster_tag_${lower(key)}="${value}"
%{ endfor ~}
%{ endif ~}

# All hosts
[all_nodes]
%{ for vm in vms ~}
${vm.config.name} ansible_host=${split("/", split("=", split(",", vm.config.ipconfig0)[0])[1])[0]} vmid=${vm.config.vmid} node_role=${vm.group} cores=${vm.config.cores} memory_mb=${vm.config.memory} disk_size=${vm.config.disk_size}
%{ endfor ~}

# Dynamic groups based on 'group' property
%{ for group_name, group_vms in all_vm_groups ~}
[${group_name}]
%{ for vm_key, vm_config in group_vms ~}
${vm_config.name}
%{ endfor ~}

%{~ endfor ~}
