# ===========================================
# roles/user_management/tasks/main.yml
# ===========================================
---
- name: Include create groups tasks
  include_tasks: create_groups.yml
  tags:
    - groups
    - create_groups

- name: Include manage users tasks
  include_tasks: manage_users.yml
  tags:
    - users
    - create_users
    - ssh_keys
    - password_policy

- name: Include cleanup users tasks
  include_tasks: cleanup_users.yml
  tags:
    - users
    - remove_users
    - cleanup
